version: '3'

services:
  recflows:
    container_name: recflows
    build: .
    command: uvicorn recflows.api.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./:/opt/recflows
    ports:
      - 8080:80
    env_file:
      - ./.env

  # tester:
  #   container_name: recflows-tester
  #   build:
  #     context: .
  #     target: tester
  #   command: tail -f /dev/null
  #   volumes:
  #     - ./:/opt/recflows
  #   env_file:
  #     - ./.env

  # ui:
  #   container_name: recflows-ui
  #   build: ui/.
  #   command: tail -f /dev/null
  #   volumes:
  #     - ./ui:/opt/recflows
  #   env_file:
  #     - ./.env

  database:
    image: mysql:8.0
    container_name: recflows-db
    environment:
      MYSQL_USER: $DATABASE_USER
      MYSQL_PASSWORD: $DATABASE_PASSWORD
      MYSQL_DATABASE: $DATABASE_DB
      MYSQL_ROOT_PASSWORD: $DATABASE_PASSWORD
    volumes:
      - recflows-db:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "$DATABASE_USER", "--password=$DATABASE_PASSWORD"]
      interval: 5s
      retries: 5

volumes:
  recflows-db:
