
def endpoints():
    return {
        "/apps": ["GET", "POST"],
        "/apps/{id}": ["GET", "PUT", "DELETE"],
        "/apps/{id}/variables": ["GET", "POST"],
        "/apps/{id}/datasets": ["GET", "POST"],
        "/apps/{id}/models": ["GET", "POST"],
        "/apps/{id}/recommenders": ["GET", "POST"],
        "/sources": ["GET", "POST"],
        "/sources/{id}": ["GET", "PUT", "DELETE"],
        "/datasets": ["GET", "POST"],
        "/datasets/{id}": ["GET", "PUT", "DELETE"],
        "/datasets/{id}:load": ["POST"],
        "/solutions": ["GET", "POST"],
        "/solutions/{id}": ["GET", "PUT", "DELETE"],
        "/solutions/{id}/tutorials": ["GET", "POST"],
        "/models": ["GET", "POST"],
        "/models/{id}": ["GET", "PUT", "DELETE"],
        "/models/{id}/versions": ["GET", "POST"],
        "/models/{id}/versions/{id}": ["GET", "PUT", "DELETE"],
        "/models/{id}/versions/{id} /recommenders": ["GET", "POST"],
        "/recommenders": ["GET", "POST"],
        "/recommenders/{id}": ["GET", "PUT", "DELETE"],
        "/recommenders/{id}:use": ["POST"],
        "/recommenders/{id}:run": ["POST"],
        "/tutorials": ["GET", "POST"],
        "/tutorials/{id}": ["GET", "PUT", "DELETE"],
        "/audits": ["GET", "POST"],
        "/audits/{id}": ["GET", "PUT", "DELETE"],
        "/audits/{id}:run": ["POST"],
        "/channels": ["GET", "POST"],
        "/channels/{id}": ["GET", "PUT", "DELETE"],
        "/variables": ["GET", "POST"],
        "/variables/{id}": ["GET", "PUT", "DELETE"],
    }